const BACKEND_URL = 'http://localhost:3000/api/contents';
const SUBMIT_FORM = 'SUBMIT_FORM';
const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR';
const CHANGE_FORM_INPUT = 'CHANGE_FORM_INPUT';
const RELOAD_FORM_PAGE = 'RELOAD_FORM_PAGE';

export {
  BACKEND_URL,
  SUBMIT_FORM,
  SUBMIT_FORM_SUCCESS,
  SUBMIT_FORM_ERROR,
  CHANGE_FORM_INPUT,
  RELOAD_FORM_PAGE,
};
