const BACKEND_URL = 'http://localhost:3000/api/contents';
const LOAD_ALL_CONTENTS = 'LOAD_ALL_CONTENTS';
const LOAD_ALL_CONTENTS_SUCCESS = 'LOAD_ALL_CONTENTS_SUCCESS';
const LOAD_ALL_CONTENTS_ERROR = 'LOAD_ALL_CONTENTS_ERROR';
const HOME_RELOAD_NEEDED = 'HOME_RELOAD_NEEDED';

export {
  BACKEND_URL,
  LOAD_ALL_CONTENTS,
  LOAD_ALL_CONTENTS_SUCCESS,
  LOAD_ALL_CONTENTS_ERROR,
  HOME_RELOAD_NEEDED,
};
